### ISSUE TITLE
Any way to stop creating AEAD pgp certs from ssh at all please?

### ISSUE THREAD

**Issue by mannp** [Mic92/ssh-to-pgp#50]
Hi

I wasn't sure if its here or in my gpg settings, but the pgp key created with ssh-to-pgp on newer versions of gpg include a seemingly non standard AEAD support.

Pass for android app uses PGPainless backend, which does not and will not support AEAD, as far as I understand it.

I wondered if it is possible to specify to create compatible pgp keys excluding AEAD?

Thanks in advance.

**Comment by Mic92** [comment]
No idea what this is or where this is coming from. I just use the golang implementation for gpg keys here: https://github.com/Mic92/ssh-to-pgp/blob/bc27953eac65f3cc4fd3e43fb106116f754cee59/convert.go#L39 The library itself is documented here: https://pkg.go.dev/golang.org/x/crypto/openpgp/packet#section-sourcefiles
Since I don't have this problem or use GPG in this way, I will not look further into this. But I will accept patches fixing this issue.
